"""Self-contained HTML report generation for telomerediff."""

from __future__ import annotations

import html as html_mod
from collections import Counter
from typing import Dict, List, Optional

from telomerediff.engine import RepeatBlock


def _esc(s: str) -> str:
    """HTML-escape a string to prevent XSS."""
    return html_mod.escape(str(s), quote=True)


_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>telomerediff Report</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
         background: #f5f5f5; color: #333; line-height: 1.6; }
  .container { max-width: 1200px; margin: 0 auto; padding: 20px; }
  h1 { color: #1a237e; margin-bottom: 8px; }
  h2 { color: #283593; margin: 24px 0 12px; border-bottom: 2px solid #e8eaf6; padding-bottom: 4px; }
  .subtitle { color: #666; margin-bottom: 24px; }
  .stats-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 16px; margin-bottom: 24px; }
  .stat-card { background: white; border-radius: 8px; padding: 20px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
  .stat-value { font-size: 2em; font-weight: bold; color: #1a237e; }
  .stat-label { color: #666; font-size: 0.9em; }
  table { width: 100%%; border-collapse: collapse; background: white; border-radius: 8px;
          overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1); margin-bottom: 24px; }
  th { background: #1a237e; color: white; padding: 12px; text-align: left; font-size: 0.85em; }
  td { padding: 10px 12px; border-bottom: 1px solid #eee; font-size: 0.85em; }
  tr:hover td { background: #f5f5ff; }
  .motif { font-family: "SF Mono", Monaco, monospace; font-weight: bold; }
  .mode-perfect { color: #2e7d32; }
  .mode-fuzzy { color: #e65100; }
  .mode-mixed { color: #6a1b9a; }
  .plot-container { background: white; border-radius: 8px; padding: 16px;
                    box-shadow: 0 1px 3px rgba(0,0,0,0.1); margin-bottom: 24px; text-align: center; }
  .plot-container img { max-width: 100%%; height: auto; }
  footer { text-align: center; color: #999; padding: 24px; font-size: 0.8em; }
  .confidence { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 0.8em; }
  .conf-high { background: #e8f5e9; color: #2e7d32; }
  .conf-med { background: #fff3e0; color: #e65100; }
  .conf-low { background: #ffebee; color: #c62828; }
</style>
</head>
<body>
<div class="container">
<h1>telomerediff Report</h1>
<p class="subtitle">%(subtitle)s</p>

<div class="stats-grid">
  <div class="stat-card"><div class="stat-value">%(total_blocks)s</div><div class="stat-label">Total Blocks</div></div>
  <div class="stat-card"><div class="stat-value">%(total_bp)s</div><div class="stat-label">Total BP</div></div>
  <div class="stat-card"><div class="stat-value">%(unique_motifs)s</div><div class="stat-label">Unique Motifs</div></div>
  <div class="stat-card"><div class="stat-value">%(reads_with_tel)s</div><div class="stat-label">Reads with Telomeres</div></div>
  <div class="stat-card"><div class="stat-value">%(avg_block_bp)s</div><div class="stat-label">Avg Block Length (bp)</div></div>
  <div class="stat-card"><div class="stat-value">%(plus_pct)s / %(minus_pct)s</div><div class="stat-label">Strand +/- (%%)</div></div>
</div>

%(plots_html)s

<h2>Top Motifs</h2>
<table>
<tr><th>Canonical Motif</th><th>k</th><th>Runs</th><th>Total BP</th><th>Strand +</th><th>Strand -</th></tr>
%(motif_rows)s
</table>

<h2>Top Blocks (by length)</h2>
<table>
<tr><th>Read</th><th>Start</th><th>End</th><th>k</th><th>Motif</th><th>Mode</th><th>Strand</th><th>Copies</th><th>BP</th><th>Confidence</th></tr>
%(block_rows)s
</table>

<footer>Generated by telomerediff</footer>
</div>
</body>
</html>
"""


def _conf_class(conf: float) -> str:
    if conf >= 0.6:
        return "conf-high"
    if conf >= 0.3:
        return "conf-med"
    return "conf-low"


def generate_html_report(
    blocks: List[RepeatBlock],
    total_bp_by_motif: Counter,
    runs_by_motif: Counter,
    by_k: Dict[int, Counter],
    by_strand: Optional[Dict[str, Counter]] = None,
    input_file: str = "",
    plot_images: Optional[Dict[str, str]] = None,
    max_block_rows: int = 200,
) -> str:
    """
    Generate a self-contained HTML report string.

    Parameters
    ----------
    blocks : list of RepeatBlock
    total_bp_by_motif : Counter
    runs_by_motif : Counter
    by_k : dict
    by_strand : dict, optional
    input_file : str
    plot_images : dict of {title: base64_png}, optional
    max_block_rows : int
    """
    total_blocks = len(blocks)
    total_bp = sum(b.run_bp for b in blocks)
    unique_motifs = len(total_bp_by_motif)
    reads_with_tel = len(set(b.read for b in blocks))
    avg_block_bp = round(total_bp / total_blocks) if total_blocks else 0

    plus_count = sum(1 for b in blocks if b.strand == "+")
    minus_count = total_blocks - plus_count
    plus_pct = round(100 * plus_count / total_blocks) if total_blocks else 0
    minus_pct = 100 - plus_pct if total_blocks else 0

    # Plots
    plots_html = ""
    if plot_images:
        for title, b64 in plot_images.items():
            if b64:
                plots_html += f'<div class="plot-container"><h3>{title}</h3>'
                plots_html += f'<img src="data:image/png;base64,{b64}" alt="{title}"></div>\n'

    # Motif table
    motif_rows = ""
    for canon, bp in total_bp_by_motif.most_common(50):
        runs = runs_by_motif.get(canon, 0)
        k_vals = [str(k) for k, cts in sorted(by_k.items()) if canon in cts]
        k_str = ",".join(k_vals) if k_vals else "?"

        strand_plus = 0
        strand_minus = 0
        if by_strand:
            sp = by_strand.get(f"{canon}:+", Counter())
            sm = by_strand.get(f"{canon}:-", Counter())
            strand_plus = sp.get("runs", 0)
            strand_minus = sm.get("runs", 0)

        motif_rows += (
            f'<tr><td class="motif">{_esc(canon)}</td><td>{_esc(k_str)}</td>'
            f"<td>{runs}</td><td>{bp:,}</td>"
            f"<td>{strand_plus}</td><td>{strand_minus}</td></tr>\n"
        )

    # Block table (top by length)
    sorted_blocks = sorted(blocks, key=lambda b: b.run_bp, reverse=True)[:max_block_rows]
    block_rows = ""
    for b in sorted_blocks:
        mode_cls = f"mode-{b.mode}"
        cc = _conf_class(b.confidence)
        block_rows += (
            f"<tr><td>{_esc(b.read[:30])}</td><td>{b.start:,}</td><td>{b.end:,}</td>"
            f"<td>{b.k}</td><td class='motif'>{_esc(b.canonical)}</td>"
            f'<td class="{_esc(mode_cls)}">{_esc(b.mode)}</td><td>{_esc(b.strand)}</td>'
            f"<td>{b.copies}</td><td>{b.run_bp:,}</td>"
            f'<td><span class="confidence {cc}">{b.confidence:.3f}</span></td></tr>\n'
        )

    subtitle = f"Input: {_esc(input_file)}" if input_file else "telomerediff analysis"

    return _HTML_TEMPLATE % dict(
        subtitle=subtitle,
        total_blocks=f"{total_blocks:,}",
        total_bp=f"{total_bp:,}",
        unique_motifs=unique_motifs,
        reads_with_tel=f"{reads_with_tel:,}",
        avg_block_bp=f"{avg_block_bp:,}",
        plus_pct=plus_pct,
        minus_pct=minus_pct,
        plots_html=plots_html,
        motif_rows=motif_rows,
        block_rows=block_rows,
    )
